# Generated by Django 4.0.6 on 2022-07-21 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationrandommodel',
            name='unique_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
