# Generated by Django 4.0.6 on 2022-07-23 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0003_applicationrandommodel__range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationrandommodel',
            name='date_close',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='applicationrandommodel',
            name='date_open',
            field=models.DateTimeField(),
        ),
    ]
